// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqfbnrstjztofxnhwrkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxZmJucnN0anp0b2Z4bmh3cmtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0OTMzNDksImV4cCI6MjA2NjA2OTM0OX0.K7wdy5-G-cm0Bl4Mw231UpPvF3eEpO1-6MxBZcIBADA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);